### ISSUE TITLE
having issue whe installing nova framework Class 'Nova\Foundation\Application' not found

### ISSUE THREAD

**Issue by kritika001** [nova-framework/framework#2002] opened 2017-12-05 11:16 UTC

**Comment by LuckyCyborg** [comment] 2017-12-05 11:56
How you did installed Nova?

And why you mock our project on your username?

**Comment by kritika001** [comment] 2017-12-06 04:22
sorry i changed the username 

i install nova form the site https://novaframework.com/documentation/v3/install
i install the nova version3 but when i run this i got error  "require(C:\xampp\htdocs\framework-3.0\vendor\autoload.php): failed to open stream: No such file or directory" and when i include vendor file i got this error
 " Uncaught Error: Class 'Nova\Foundation\Application' not found in C:\xampp\htdocs\framework-3.0\app\Start.php:49 "
i am stuck from this please suggest me

**Comment by dcblogdev** [comment] 2017-12-06 09:18
did you run: 

```composer install```

**Comment by LuckyCyborg** [comment] 2017-12-06 09:36
Same suggestion.

Also, to note that the composer vendor files are a must, for the today Nova applications.

**Comment by kritika001** [comment] 2017-12-06 11:29
yes i run this command....but don't get the vendor folder ....however i got this error on running every command

**Comment by kritika001** [comment] 2017-12-06 11:47
![capture](https://user-images.githubusercontent.com/34264331/33660214-1a0ac4f4-daa9-11e7-8ee3-90a9c739da23.PNG)

**Comment by dcblogdev** [comment] 2017-12-06 12:33
okay, it appears you don't have GIT installed on your computer.

**Comment by kritika001** [comment] 2017-12-06 12:57
so i need to intall it??

**Comment by dcblogdev** [comment] 2017-12-06 12:59
yes git is required by composer, go to https://git-scm.com/book/en/v2/Getting-Started-Installing-Git to get it.

**Comment by LuckyCyborg** [comment] 2017-12-06 13:24
I think we can close this issue, because we already found the cause.

@kritika001 If you have any other questions, feel free to open another issue, but much better, if you do not have to report a framework bug, I invite you in our forum: https://novaframework.com/forum

**Closed as completed by LuckyCyborg** 2017-12-06 13:24 UTC

**Comment by kritika001** [comment] 2017-12-07 04:55
thanks @daveismyname  it works  having vendor folder now :)
